"""create initial schema

Revision ID: 62449d72526f
Revises:
Create Date: 2026-08-20 12:52:46.801869
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "62449d72526f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("object_type", sa.String(length=80), nullable=False),
        sa.Column("object_id", sa.String(length=80), nullable=False),
        sa.Column("request_id", sa.String(length=80), nullable=True),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "domains",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("secret_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["api_clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_prefix"),
    )
    op.create_index(op.f("ix_api_keys_client_id"), "api_keys", ["client_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("moderation_state", sa.String(length=20), nullable=False),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("moderated_by", sa.String(length=160), nullable=True),
        sa.Column("decision_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["api_clients.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "moderation_state IN ('queued', 'accepted', 'rejected')",
            name="ck_observations_moderation_state",
        ),
        sa.CheckConstraint(
            "(moderation_state = 'queued' AND moderated_at IS NULL AND moderated_by IS NULL AND decision_reason IS NULL) OR (moderation_state <> 'queued' AND moderated_at IS NOT NULL AND moderated_by IS NOT NULL AND decision_reason IS NOT NULL)",
            name="ck_observations_moderation_fields",
        ),
        sa.UniqueConstraint("client_id", "idempotency_key", name="uq_observation_idempotency"),
    )
    op.create_index(op.f("ix_observations_client_id"), "observations", ["client_id"], unique=False)
    op.create_index(
        "ix_observations_queue",
        "observations",
        ["moderation_state", "received_at", "id"],
        unique=False,
    )
    op.create_table(
        "rate_windows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["api_clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "window_start", name="uq_rate_window"),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("region", sa.String(length=2), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("region ~ '^[A-Z]{2}$'", name="ck_routes_region"),
        sa.CheckConstraint("outcome = 'cancel_subscription'", name="ck_routes_outcome"),
        sa.UniqueConstraint("service_id", "outcome", "region", "platform", name="uq_route_variant"),
    )
    op.create_index(op.f("ix_routes_service_id"), "routes", ["service_id"], unique=False)
    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "event_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("secret_salt", sa.LargeBinary(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["api_clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_subscriptions_client_id"),
        "webhook_subscriptions",
        ["client_id"],
        unique=False,
    )
    op.create_table(
        "route_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("publication_state", sa.String(length=20), nullable=False),
        sa.Column("trust_state", sa.String(length=20), nullable=False),
        sa.Column("status_version", sa.Integer(), nullable=False),
        sa.Column("entry_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "graph",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "best_route",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "friction",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=12), nullable=False),
        sa.Column("change_summary", sa.String(length=280), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("revision > 0", name="ck_revisions_positive_revision"),
        sa.CheckConstraint("status_version > 0", name="ck_revisions_positive_status_version"),
        sa.CheckConstraint(
            "publication_state IN ('draft', 'published', 'superseded', 'withdrawn')",
            name="ck_revisions_publication_state",
        ),
        sa.CheckConstraint(
            "trust_state IN ('provisional', 'verified', 'stale')", name="ck_revisions_trust_state"
        ),
        sa.CheckConstraint("entry_url LIKE 'https://%'", name="ck_revisions_https_entry"),
        sa.CheckConstraint("fingerprint ~ '^[a-f0-9]{64}$'", name="ck_revisions_fingerprint"),
        sa.CheckConstraint(
            "review_due_at IS NULL OR verified_at IS NULL OR review_due_at > verified_at",
            name="ck_revisions_review_after_verification",
        ),
        sa.CheckConstraint(
            "publication_state = 'draft' OR (verified_at IS NOT NULL AND review_due_at IS NOT NULL AND published_at IS NOT NULL)",
            name="ck_revisions_published_dates",
        ),
        sa.UniqueConstraint("route_id", "fingerprint", name="uq_route_revision_fingerprint"),
        sa.UniqueConstraint("route_id", "id", name="uq_route_revision_identity"),
        sa.UniqueConstraint("route_id", "revision", name="uq_route_revision_number"),
    )
    op.create_index(
        "ix_revision_publication_trust",
        "route_revisions",
        ["publication_state", "trust_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_revisions_route_id"), "route_revisions", ["route_id"], unique=False
    )
    op.create_foreign_key(
        "fk_routes_current_revision",
        "routes",
        "route_revisions",
        ["id", "current_revision_id"],
        ["route_id", "id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "challenge_assignments",
        sa.Column("challenge_date", sa.Date(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["revision_id"], ["route_revisions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("challenge_date"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_table(
        "change_events",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=280), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["revision_id"], ["route_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_change_events_route_id"), "change_events", ["route_id"], unique=False)
    op.create_table(
        "verification_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("verifier", sa.String(length=120), nullable=False),
        sa.Column("environment", sa.String(length=280), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("evidence_ref", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["revision_id"], ["route_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_events_revision_id"),
        "verification_events",
        ["revision_id"],
        unique=False,
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["change_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["webhook_subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subscription_id", "event_id", name="uq_delivery_subscription_event"),
    )
    op.create_index(
        "ix_delivery_due", "webhook_deliveries", ["state", "next_attempt_at"], unique=False
    )
    op.execute(
        """
        CREATE FUNCTION exitroute_protect_revision_content() RETURNS trigger AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            IF OLD.publication_state <> 'draft' THEN
              RAISE EXCEPTION 'published route revision content is immutable';
            END IF;
            RETURN OLD;
          END IF;
          IF OLD.publication_state <> 'draft' AND (
            NEW.route_id IS DISTINCT FROM OLD.route_id OR
            NEW.revision IS DISTINCT FROM OLD.revision OR
            NEW.entry_url IS DISTINCT FROM OLD.entry_url OR
            NEW.graph IS DISTINCT FROM OLD.graph OR
            NEW.best_route IS DISTINCT FROM OLD.best_route OR
            NEW.friction IS DISTINCT FROM OLD.friction OR
            NEW.algorithm_version IS DISTINCT FROM OLD.algorithm_version OR
            NEW.fingerprint IS DISTINCT FROM OLD.fingerprint OR
            NEW.confidence IS DISTINCT FROM OLD.confidence OR
            NEW.change_summary IS DISTINCT FROM OLD.change_summary OR
            NEW.verified_at IS DISTINCT FROM OLD.verified_at OR
            NEW.review_due_at IS DISTINCT FROM OLD.review_due_at OR
            NEW.published_at IS DISTINCT FROM OLD.published_at
          ) THEN
            RAISE EXCEPTION 'published route revision content is immutable';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER protect_route_revision_content
        BEFORE UPDATE OR DELETE ON route_revisions
        FOR EACH ROW EXECUTE FUNCTION exitroute_protect_revision_content();

        CREATE FUNCTION exitroute_reject_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'append-only table cannot be updated or deleted';
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER protect_audit_events
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION exitroute_reject_mutation();

        CREATE TRIGGER protect_change_events
        BEFORE UPDATE OR DELETE ON change_events
        FOR EACH ROW EXECUTE FUNCTION exitroute_reject_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER protect_change_events ON change_events")
    op.execute("DROP TRIGGER protect_audit_events ON audit_events")
    op.execute("DROP FUNCTION exitroute_reject_mutation()")
    op.execute("DROP TRIGGER protect_route_revision_content ON route_revisions")
    op.execute("DROP FUNCTION exitroute_protect_revision_content()")
    op.drop_index("ix_delivery_due", table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_verification_events_revision_id"), table_name="verification_events")
    op.drop_table("verification_events")
    op.drop_index(op.f("ix_change_events_route_id"), table_name="change_events")
    op.drop_table("change_events")
    op.drop_table("challenge_assignments")
    op.drop_constraint("fk_routes_current_revision", "routes", type_="foreignkey")
    op.drop_index(op.f("ix_route_revisions_route_id"), table_name="route_revisions")
    op.drop_index("ix_revision_publication_trust", table_name="route_revisions")
    op.drop_table("route_revisions")
    op.drop_index(op.f("ix_webhook_subscriptions_client_id"), table_name="webhook_subscriptions")
    op.drop_table("webhook_subscriptions")
    op.drop_index(op.f("ix_routes_service_id"), table_name="routes")
    op.drop_table("routes")
    op.drop_table("rate_windows")
    op.drop_index("ix_observations_queue", table_name="observations")
    op.drop_index(op.f("ix_observations_client_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_api_keys_client_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("services")
    op.drop_table("audit_events")
    op.drop_table("api_clients")
    # ### end Alembic commands ###
